# Generated by Django 3.0.4 on 2021-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='title', max_length=600)),
                ('post_content', models.CharField(default='content', max_length=1024)),
                ('tag', models.CharField(default='default', max_length=255)),
                ('author', models.CharField(default='admin', max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
